
# --------------------------------- # 
# |         Verre2OuiSki          | # 
# --------------------------------- # 




# set maximum delay to say welcome like below

# exemple: 00:00:00 (H:m:s)

sayWelcomeTimer: 00:00:10