name: HenoriaRanksss
version: 1.0.0
main: HenoriaRanks\Main
api: 3.17.0

author: Verre2OuiSki
description: Ranks and permissions systeme for Henoria.
website: https://twitter.com/Verre2OuiSki

# -----------------------------------------------

# kjqnsdhjbqsd